# GitHub Actions workflow for CI/CD using Docker
name: Docker-based CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-tests-and-deploy:
    name: Run Tests & Deploy to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the project repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build the Docker image
      - name: Build Docker image for testing
        run: docker build -t jest-testing .

      # Step 4: Run tests inside the container
      - name: Run Jest tests in Docker container
        run: docker run --rm jest-testing npm test

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 6: Tag the image for Docker Hub
      - name: Tag image for Docker Hub
        run: docker tag jest-testing ${{ secrets.DOCKERHUB_USERNAME }}/jest-testing:latest

      # Step 7: Push the image to Docker Hub
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/jest-testing:latest
      
      # Step 8: Clean up Docker images
      - name: Clean up Docker images
        run: docker rmi jest-testing ${{ secrets.DOCKERHUB_USERNAME }}/jest-testing:latest || true
